// lib/firebase_options.dart
// This file would be generated by the FlutterFire CLI
// Placeholder for the Firebase configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with your actual Firebase configuration values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtobNlcxJk46tMZKVASqx32d0fFjV15E4',
    appId: '1:706457137235:web:1e8f157ce627d3e02956a6',
    messagingSenderId: '706457137235',
    projectId: 'skrybe-1cb67',
    authDomain: 'noreply@skrybe-1cb67.firebaseapp.com',
    storageBucket: 'YOUR-STORAGE-BUCKET', // Expects me to pay
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtobNlcxJk46tMZKVASqx32d0fFjV15E4',
    appId: '1:706457137235:android:aacd9daf5f211ea52956a6',
    messagingSenderId: '706457137235',
    projectId: 'skrybe-1cb67',
    storageBucket: 'YOUR-STORAGE-BUCKET', // Expects me to pay
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtobNlcxJk46tMZKVASqx32d0fFjV15E4',
    appId: '1:706457137235:ios:e52ce091ba40c22c2956a6',
    messagingSenderId: '706457137235',
    projectId: 'skrybe-1cb67',
    storageBucket: 'YOUR-STORAGE-BUCKET', // Expects me to pay
    iosClientId: 'YOUR-IOS-CLIENT-ID', // Doesn't exist yet
    iosBundleId: 'YOUR-IOS-BUNDLE-ID', // Doesn't exist yet
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtobNlcxJk46tMZKVASqx32d0fFjV15E4',
    appId: 'YOUR-APP-ID',
    messagingSenderId: '706457137235',
    projectId: 'skrybe-1cb67',
    storageBucket: 'YOUR-STORAGE-BUCKET', // Expects me to pay
    iosClientId: 'YOUR-IOS-CLIENT-ID', // Doesn't exist yet
    iosBundleId: 'YOUR-IOS-BUNDLE-ID', // Doesn't exist yet
  );
}
